[package]
name = "rusty_sword"
version = "0.2.0"
authors = [ "Nathan Stocks <nathan.stocks@gmail.com>" ]
edition = "2021"

[dependencies]
crossbeam = "0.8.1"
crossterm = "0.28.1"
rand = "0.9.1"
rusty_audio = "1.1.1"
